Repository vtex-sites/base.store, pull requests merged in 2022-03, with the labels that each got.

#368 chore: Performance improvements by sections
  CHANGELOG.md
  src/components/sections/Section/Section.tsx
  src/components/sections/Section/index.ts
  src/components/sections/Section/section.scss
  src/pages/index.tsx
  src/pages/s.tsx
  src/pages/{StoreCollection.slug}.tsx
  src/pages/{StoreProduct.slug}/p.tsx
Labels: performance

#378 chore: Add icons to unique svg file and remove from final bundle
  CHANGELOG.md
  README.md
  package.json
  src/components/cart/CartItem/CartItem.tsx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/cart/CartToggle/CartToggle.tsx
  src/components/cart/EmptyCart/EmptyCart.tsx
  src/components/common/Alert/Alert.tsx
  src/components/common/Footer/footer.scss
  src/components/common/IconSVG/IconSVG.tsx
  src/components/common/IconSVG/index.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/SearchInput/SearchInput.tsx
  src/components/product/OutOfStock/OutOfStock.tsx
  src/components/search/Filter/Filter.tsx
  src/components/search/Filter/filter.scss
  src/components/sections/Hero/Hero.tsx
  src/components/sections/Incentives/IncentivesFooter.tsx
  src/components/sections/Incentives/IncentivesHeader.tsx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/Accordion/AccordionItem.tsx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/BuyButton/BuyButton.tsx
  src/components/ui/QuantitySelector/QuantitySelector.tsx
  src/components/ui/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/SignInLink/SignInLink.tsx
  src/pages/{StoreCollection.slug}.tsx
  static/icons/icons.svg
  yarn.lock
Labels: enhancement, performance

#383 refactor: `Tiles` component to use a semantic list element
  CHANGELOG.md
  src/components/ui/Tiles/Tile.tsx
  src/components/ui/Tiles/Tiles.tsx
Labels: enhancement

#395 chore: Accept performance drop
  package.json
  src/components/product/ProductGrid/ProductGrid.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/useDelayedFacets.ts
  yarn.lock
Labels: performance

#411 chore: Remove frontend computing
  CHANGELOG.md
  package.json
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductGrid/ProductGrid.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/Badge/DiscountBadge.tsx
  src/sdk/product/useDiscountPercent.ts
  src/sdk/product/useProductLink.ts
  yarn.lock
Labels: performance

#425 feat: Product Card Theming
  CHANGELOG.md
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductCard/product-card.scss
  src/components/sections/ProductGallery/product-gallery.scss
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/skeletons/ProductCardSkeleton/ProductCardSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/ProductTileSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTilesSkeleton.tsx
  src/components/ui/Tiles/tiles.scss
Labels: enhancement

#401 chore: Improve images performance
  CHANGELOG.md
  gatsby-config.js
  package.json
  src/components/cart/CartItem/CartItem.tsx
  src/components/product/ProductCard/ProductCard.tsx
  src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
  src/components/sections/Hero/Hero.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/Image/Image.tsx
  src/components/ui/Image/ImageWithArtDirection.tsx
  src/components/ui/Image/image.scss
  src/components/ui/Image/index.tsx
  src/components/ui/Image/thumborUrlBuilder.ts
  src/components/ui/Image/useImage.ts
  src/components/ui/ImageGallery/ImageGallery.tsx
  src/components/ui/SkuSelector/SkuSelector.tsx
  yarn.lock
Labels: performance
