Repository vtex-sites/base.store, pull requests merged in 2022-01, with the labels that each got.

#201 feat: Adds SROnly component
  src/components/product/ProductCard/ProductCard.tsx
  src/components/ui/Price/Price.tsx
  src/components/ui/SROnly/SROnly.tsx
  src/components/ui/SROnly/index.tsx
  src/components/ui/SROnly/sr-only.scss
Labels: enhancement

#200 Feat: Style the PDP
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  cypress/integration/analytics.test.js
  src/components/product/ProductCard/ProductCard.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.scss
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/ProductTitle/ProductTitle.tsx
  src/components/ui/ProductTitle/index.tsx
  src/components/ui/ProductTitle/product-title.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/pages/{StoreProduct.slug}/p.tsx
  src/styles/global.scss
  src/styles/grid.scss
  src/styles/pages/index.scss
Labels: enhancement

#177 Feat: Implements and Styles footer
  cypress.json
  cypress/integration/plp.test.js
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterLinks.tsx
  src/components/common/Footer/Icons.tsx
  src/components/common/Footer/footer.scss
  src/components/common/Footer/index.tsx
  src/components/common/Footer/useWindowDimensions.ts
  src/components/sections/Incentives/Incentives.tsx
  src/components/sections/Incentives/IncentivesFooter.tsx
  src/components/sections/Incentives/IncentivesHeader.tsx
  src/components/sections/Incentives/incentives.scss
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/styles/pattern-library.scss
Labels: faststore

#250 Fix: Attempt to fix PLP Lighthouse CLS issue
  src/Layout.tsx
  src/styles/global.scss
Labels: bug

#251 Remove duplicate product name on PDP
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/pages/{StoreProduct.slug}/p.tsx
Labels: bug

#268 Remove dup adding/removing cart items in the PLP tests block
  cypress/integration/cart.test.js
Labels: enhancement

#274 Fix Lighthouse PDP flaky error in console failure
  gatsby-ssr.js
Labels: bug

#282 Fix: MiniCart - Empty State
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/cart/EmptyCart/EmptyCart.tsx
Labels: bug
