Repository vtex-sites/base.store, pull requests merged in 2022-02, with the labels that each got.

#284 [FSSS-156] Simplify some integration tests
  cypress/integration/analytics.test.js
Labels: enhancement

#297 Fix a SonarQube warning
  src/components/ui/QuantitySelector/QuantitySelector.tsx
Labels: enhancement

#344 fix: Scroll lock when transitioning on mobile via slide-over nav
  CHANGELOG.md
  src/components/ui/SlideOver/SlideOver.tsx
Labels: bug

#357 feat: webpack analyser
  CHANGELOG.md
  gatsby-config.js
  package.json
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/Icons.tsx
  static/icons/ApplePay.svg
  static/icons/Diners.svg
  static/icons/EloCard.svg
  static/icons/Facebook.svg
  static/icons/FastStore.png
  static/icons/GooglePay.svg
  static/icons/Instagram.svg
  static/icons/Mastercard.svg
  static/icons/PayPal.svg
  static/icons/Pinterest.svg
  static/icons/Stripe.svg
  static/icons/Twitter.svg
  static/icons/Visa.svg
  yarn.lock
Labels: performance

#360 fix: remove from cart and analytics events
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  package.json
  src/components/cart/CartItem/CartItem.tsx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/Toast/Toast.tsx
  src/sdk/cart/useBuyButton.ts
  src/sdk/cart/useCart.ts
  src/sdk/cart/useRemoveButton.ts
  src/sdk/cart/validate.ts
  src/sdk/ui/index.tsx
  yarn.lock
Labels: bug

#365 fix: Breadcrumb's invalid HTML dividers
  CHANGELOG.md
  package.json
  src/components/ui/Breadcrumb/breadcrumb.scss
  yarn.lock
Labels: bug

#366 fix: Cart item availability
  package.json
  yarn.lock
Labels: bug
