Repository vtex-sites/base.store, pull requests merged in 2022-04, with the labels that each got.

#442 feat: Button Theming
  CHANGELOG.md
  README.md
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/cart/CartToggle/CartToggle.tsx
  src/components/cart/CartToggle/cart-toggle.scss
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.scss
  src/components/product/ProductCard/ProductCard.tsx
  src/components/search/Filter/Filter.tsx
  src/components/search/Filter/filter.scss
  src/components/sections/BannerText/BannerText.tsx
  src/components/sections/Hero/Hero.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/product-gallery.scss
  src/components/ui/Alert/alert.scss
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/ButtonBuy.tsx
  src/components/ui/Button/ButtonIcon.tsx
  src/components/ui/Button/ButtonLink.tsx
  src/components/ui/Button/ButtonSignIn.tsx
  src/components/ui/Button/button.scss
  src/components/ui/Button/buttons.scss
  src/components/ui/Button/index.tsx
  src/components/ui/BuyButton/buy-button.scss
  src/components/ui/BuyButton/index.tsx
  src/components/ui/Hero/hero.scss
  src/components/ui/IconButton/IconButton.tsx
  src/components/ui/IconButton/icon-button.scss
  src/components/ui/IconButton/index.ts
  src/components/ui/Link/Link.tsx
  src/components/ui/Link/link.scss
  src/components/ui/SignInLink/index.ts
  src/styles/global/components.scss
  src/styles/global/tokens.scss
Labels: enhancement

#445 chore: Reduce PLP blocking time
  CHANGELOG.md
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/ProductGalleryPage.tsx
  src/components/sections/ProductGallery/usePageProducts.ts
  src/sdk/graphql/prefetchQuery.ts
  src/sdk/product/useProductsQuery.ts
Labels: performance

#431 feat: Move shelf client side
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  src/components/product/ProductGrid/ProductGrid.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/ProductGalleryPage.tsx
  src/components/sections/ProductGallery/useGalleryQuery.ts
  src/components/sections/ProductGallery/usePageProducts.ts
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/skeletons/ProductShelfSkeleton/ProductShelfSkeleton.tsx
  src/pages/index.tsx
  src/pages/{StoreCollection.slug}.tsx
  src/pages/{StoreProduct.slug}/p.tsx
  src/sdk/analytics/hooks/useViewItemListEvent.ts
  src/sdk/product/useProductsQuery.ts
  src/sdk/search/Sentinel.tsx
  src/server/index.js
Labels: enhancement

#450 Updates CHANGELOG to match base.store's March Release Notes
  CHANGELOG.md
Labels: documentation

#456 [BREAKING CHAGE]: Migrate to Gatsby v4
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  cypress/integration/performance.test.js
  cypress/integration/plp.test.js
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/product/ProductCard/ProductCard.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/Section/Section.tsx
  src/components/ui/Button/ButtonSignIn.tsx
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
  src/pages/s.tsx
  src/sdk/ui/modal/Provider.tsx
  src/server/index.js
  vtex.env
  yarn.lock
Labels: enhancement

#459 [BREAKING CHANGE]: Move Gatsby config files to Typescript
  .eslintrc
  CHANGELOG.md
  gatsby-browser.tsx
  gatsby-config.ts
  gatsby-node.js
  gatsby-node.ts
  gatsby-ssr.tsx
  package.json
  src/components/sections/Newsletter/Newsletter.tsx
  src/pages/[...slug].tsx
  src/sdk/ui/index.tsx
  src/server/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, Gatsby 4

#461 chore: Upgrade to React18
  CHANGELOG.md
  package.json
  tsconfig.json
  vtex.env
  yarn.lock
Labels: enhancement, Gatsby 4

#430 chore: Adjust stylelint rules
  CHANGELOG.md
  src/components/cart/CartItem/cart-item.scss
  src/components/cart/CartSidebar/cart-sidebar.scss
  src/components/common/Footer/footer.scss
  src/components/product/ProductCard/product-card.scss
  src/components/search/History/search-history.scss
  src/components/search/SuggestionProductCard/suggestion-product-card.scss
  src/components/search/Suggestions/suggestions.scss
  src/components/sections/BannerText/banner-text.scss
  src/components/sections/ProductDetails/product-details.scss
  src/components/sections/ProductShelf/product-shelf.scss
  src/components/skeletons/SkeletonElement/skeleton-element.scss
  src/components/ui/Accordion/accordion.scss
  src/components/ui/Badge/badge.scss
  src/components/ui/Button/button.scss
  src/components/ui/Checkbox/checkbox.scss
  src/components/ui/EmptyState/empty-state.scss
  src/components/ui/Price/price.scss
  src/components/ui/ProductTitle/product-title.scss
  src/components/ui/QuantitySelector/quantity-selector.scss
  src/components/ui/SROnly/sr-only.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/components/ui/SlideOver/slide-over.scss
  src/styles/global/resets.scss
  src/styles/global/tokens.scss
  src/styles/global/typography.scss
  stylelint.config.js
Labels: depends on

#420 Fix: slide over scroll behavior
  CHANGELOG.md
  cypress/integration/cart.test.js
  src/sdk/ui/modal/Provider.tsx
  src/sdk/ui/modal/modal-provider.scss
  src/styles/global/components.scss
  src/styles/global/layout.scss
Labels: bug

#448 Feat: Quantity Selector Theming
  CHANGELOG.md
  src/components/product/ProductCard/product-card.scss
  src/components/sections/ProductShelf/product-shelf.scss
  src/components/ui/Button/button.scss
  src/components/ui/QuantitySelector/QuantitySelector.tsx
  src/components/ui/QuantitySelector/quantity-selector.scss
  src/styles/global/tokens.scss
Labels: enhancement
